### ISSUE TITLE
Code-switched data

### ISSUE THREAD

**Issue by smontariol** [SamiaTouileb/NArabizi#1]
Hi!
Thank you for sharing your dataset, I was wondering if the code-switched version of the treebank is available?

**Comment by SamiaTouileb** [comment]
Hi,
The entire treebank is code-switched. The NArabizi version (written in Latin), the transliterations to Arabic script, and the code-switched in script version all include code-switching :) 
Just check the columns 4 and 5 of the NArabizi data  (the conllu files), and you'll find them.
